# Composite Action: Setup Environment
# Reusable setup for Python, Solc, Foundry, and project dependencies
# Used by all workflows to ensure consistent environment

name: 'Setup Environment'
description: 'Set up Python, Solc, Foundry and install dependencies'

inputs:
  python-version:
    description: 'Python version'
    required: false
    default: '3.11'
  solc-version:
    description: 'Solc version'
    required: false
    default: '0.8.30'
  install-forge-deps:
    description: 'Install Forge dependencies'
    required: false
    default: 'true'

runs:
  using: 'composite'
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}
        cache: 'pip'

    - name: Install Python dependencies
      shell: bash
      run: pip install -r requirements.txt

    - name: Install Foundry
      uses: foundry-rs/foundry-toolchain@v1
      with:
        version: nightly

    - name: Install Solc
      shell: bash
      run: |
        pip install solc-select
        solc-select install ${{ inputs.solc-version }}
        solc-select use ${{ inputs.solc-version }}
        echo "Solc version: $(solc --version | head -2 | tail -1)"

    - name: Install Forge dependencies
      if: ${{ inputs.install-forge-deps == 'true' }}
      shell: bash
      working-directory: foundry
      run: forge install --no-git
