# Composite Action: Setup Environment
# Reusable setup for Python, Solc, Foundry, and project dependencies
# Used by all workflows to ensure consistent environment

name: 'Setup Environment'
description: 'Set up Python, Solc, Foundry and install dependencies'

inputs:
  python-version:
    description: 'Python version'
    required: false
    default: '3.11'
  solc-version:
    description: 'Solc version'
    required: false
    default: '0.8.30'
  install-forge-deps:
    description: 'Install Forge dependencies'
    required: false
    default: 'true'

runs:
  using: 'composite'
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}
        cache: 'pip'

    - name: Install Python dependencies
      shell: bash
      run: pip install -r requirements.txt

    - name: Install Vyper submodule
      shell: bash
      run: |
        # Install local Vyper fork in editable mode
        # Required: patched version with phi ordering, log effects, Yul opcodes
        pip install -e vyper/
        python -c "import vyper; print(f'Vyper {vyper.__version__} installed')"

    - name: Install Foundry
      uses: foundry-rs/foundry-toolchain@v1
      with:
        version: nightly

    - name: Install Solc
      shell: bash
      run: |
        pip install solc-select
        solc-select install ${{ inputs.solc-version }}
        solc-select use ${{ inputs.solc-version }}
        echo "Solc version: $(solc --version | head -2 | tail -1)"

    - name: Install Forge dependencies
      if: ${{ inputs.install-forge-deps == 'true' }}
      shell: bash
      working-directory: foundry
      run: |
        # Check if lib/forge-std exists (from submodules)
        if [ -d "lib/forge-std/src" ]; then
          echo "✓ forge-std already installed via submodules"
        else
          echo "Installing forge-std..."
          forge install foundry-rs/forge-std --no-commit 2>/dev/null || forge install foundry-rs/forge-std || true
        fi
        # Verify installation
        if [ ! -f "lib/forge-std/src/Test.sol" ]; then
          echo "⚠ forge-std not found, installing..."
          rm -rf lib/forge-std
          git clone --depth 1 https://github.com/foundry-rs/forge-std.git lib/forge-std
        fi
        echo "✓ forge-std ready: $(ls lib/forge-std/src/*.sol | wc -l) files"
